// Creacion de usuario con admin

ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER CAMERA_STORE
IDENTIFIED BY "MANG.OSTAS"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS;


 -- PERMISOS PARA EL USUARIO CAMERA_STORE
GRANT CREATE SESSION, CREATE TABLE, CREATE USER  TO CAMERA_STORE;
GRANT CREATE SEQUENCE TO CAMERA_STORE;
GRANT CREATE ROLE TO CAMERA_STORE;

GRANT CREATE SESSION TO CAMERA_STORE WITH ADMIN OPTION;
GRANT CREATE USER TO CAMERA_STORE WITH ADMIN OPTION;
GRANT CREATE VIEW TO CAMERA_STORE WITH ADMIN OPTION;
GRANT CREATE ROLE TO CAMERA_STORE WITH ADMIN OPTION;


// Ingresamos con el usuario CAMERA_STORE y creamos y poblamos la tabla.

drop table PRODUCT;

CREATE TABLE PRODUCT (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100),
    price NUMBER,
    category VARCHAR2(20),
    description VARCHAR2(200)
);


INSERT INTO Product (name, price, category, description) VALUES ('Nikon D3500', 450, 'Cameras', 'Entry-level DSLR with 24.2 MP sensor and 1080p video.');
INSERT INTO Product (name, price, category, description) VALUES ('Canon EOS Rebel T7', 500, 'Cameras', '24.1 MP DSLR with built-in Wi-Fi and 18-55mm lens.');
INSERT INTO Product (name, price, category, description) VALUES ('Sony Alpha a6000', 650, 'Mirrorless', 'Compact mirrorless camera with fast autofocus and 24.3 MP resolution.');
INSERT INTO Product (name, price, category, description) VALUES ('Fujifilm X-T200', 700, 'Mirrorless', 'Stylish mirrorless with 3.5-inch touchscreen and 4K video.');
INSERT INTO Product (name, price, category, description) VALUES ('GoPro HERO9', 400, 'Action Cameras', 'Waterproof action camera with 5K video and HyperSmooth stabilization.');